apiVersion: v1
kind: Service
metadata:
  name: {{ include "mykadoo.fullname" . }}-api
  labels:
    {{- include "mykadoo.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
      name: {{ .Values.service.api.name }}
  selector:
    {{- include "mykadoo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
