apiVersion: v1
kind: Service
metadata:
  name: {{ include "mykadoo.fullname" . }}-web
  labels:
    {{- include "mykadoo.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
      protocol: TCP
      name: {{ .Values.service.web.name }}
  selector:
    {{- include "mykadoo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
